### ISSUE TITLE
Do we need pclose when we use xquote "`"?

### ISSUE THREAD

**Issue by kjunichi** [iij/mruby-io#37]
Hi, mruby-io is very helpful for me.

in mrblib/kernel.rb

said that 

```rb
module Kernel
def self.`(cmd)
  IO.popen(cmd) { |io| io.read }
end
```

I'm not expert at Unix and Linux,but popen's manual pages says retunrn value needs to be pclose.

to tell the truth,
when I wote server side code in Trusterd HTTP2 web server.
I wrote the code to use  `ldd`.
one request test is Ok.
but many requests sends,the test is fail.
I checked it,I found many ldd processes.

Thank you.

```

```

**Comment by tsahara** [comment]
It is a bug.  Because `IO.popen` does not call popen(3), we don't need to (cannot) call pclose(3) to close pipes.  We should remove zombie processes in other ways.

Thank you for reporting.

**Comment by kjunichi** [comment]
Not at all.
Thank you quick reply.

Is there any reason not to wait/waitpid in mrb_io_s_popen?

- https://github.com/iij/mruby-io/blob/master/src/io.c#L272-273

**Comment by tsahara** [comment]
Child processes can be alive in `mrb_io_s_popen`.  We should wait(2) for processes when we *close* pipes.

**Comment by kjunichi** [comment]
Thank you very much!

It works well in my project.
Now I have no need to write 

```rb
Signal.trap(:SIGCLD, :SIG_IGN)
```

before 

```
`hoge`
```
