### ISSUE TITLE
IO#eof? raises IOError just after IO.new

### ISSUE THREAD

**Issue by tagomoris** [iij/mruby-io#66]
It is caused by `sysread(1)` and `_ungets(char)`.
`sysread` doesn't increment `@pos`, but `_ungets(char)` raises IOError if `@pos == 0`.

This problem makes us impossible to write code like below:
```ruby
f = File.open(filename, 'r')
until f.eof?
  f.read(bytes)
  # ...
end
```

**Comment by tsahara** [comment]
Thank you for reporting it!
