### ISSUE TITLE
Fail: IO.sysopen, IO#sysread (mrbgems: mruby-io)

### ISSUE THREAD

**Issue by katzer** [iij/mruby-io#83]
Hi,

the test suite fails with mruby 1.2.0

> Fail: IO.sysopen, IO#sysread (mrbgems: mruby-io)
Total: 672
   OK: 671
   KO: 1
Crash: 0
rake aborted!

With mruby-head its green.

BTW, what do you think about running the tests on travis for both mruby-1.2.0 and mruby-head?

**Comment by tsahara** [comment]
fixed by https://github.com/iij/mruby-io/commit/3a73a5849388fe908af7131804f9fc7f55472651
