### ISSUE TITLE
Cannot call open from File class

### ISSUE THREAD

**Issue by WaveformDelta** [iij/mruby-io#91]
I am unable to call ``File.open`` from the C API. The following code works:
```
    char command[256];
    sprintf(command, "@f = File.open(\"%s\", \"rb\")", filePath);

    mrb_state* mrb = mrb_open();
    mrb_value result = mrb_load_string(mrb, command);
    result = mrb_load_string(mrb, "p \"First byte: \" + @f.read(1)");
```
But the following code, which I believe should be equivalent, crashes:
```
    struct RClass* file_class = mrb_class_get(mrb, "File");
    mrb_value filepath = mrb_str_new_cstr(mrb, filePath);
    mrb_value open_mode = mrb_str_new_cstr(mrb, "rb");
    mrb_value fp = mrb_funcall(mrb, mrb_obj_value(file_class), "open", 2, &filepath, &open_mode);
```
Specifically, the call to ``mrb_funcall`` throws an exception in ``class.c(mrb_method_search_vm())``

Note that the method ``open`` is definitely defined on ``File``, because the following returns true:
```
    mrb_bool obj_resp = mrb_obj_respond_to(mrb, file_class, mrb_intern_cstr(mrb, "open"));
```

**Comment by tsahara** [comment]
`mrb_funcall`'s varargs are of type mrb_value, not pointer to mrb_value.  Try removing '&' from `&filepath` and `&open_mode` please.

**Comment by WaveformDelta** [comment]
That worked, thank you!
